#!/usr/bin/env sh
set -e

. "$(dirname "$0")/lib/functions.sh"

current_branch="$(git symbolic-ref --short HEAD)"
base_branch="$(get_base_branch)"

if ! git diff --quiet "$base_branch" "$current_branch"; then
  bun run type-check
  bun run lint
fi